CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "role" varchar NOT NULL,
  "gender" varchar(10) NOT NULL,
  "avatar" varchar,
  "email" varchar(50) UNIQUE NOT NULL,
  "isActive" bit,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "empresa" (
  "empresa_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_empresa" varchar(50) NOT NULL,
  "direccion" varchar(50) NOT NULL,
  "region_id" integer,
  "comuna_id" integer
);

CREATE TABLE "product" (
  "product_id" INT PRIMARY KEY,
  "nom_producto" varchar NOT NULL,
  "codigo" varchar NOT NULL,
  "nom_catalogo" varchar,
  "pagina_catalogo" integer,
  "descripcion" varchar,
  "imagen" varchar(250) NOT NULL,
  "area_id" integer,
  "empresa_id" integer,
  "search_by" integer
);

CREATE TABLE "area" (
  "area_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_area" varchar(50) NOT NULL,
  "descripcion" varchar
);

CREATE TABLE "institucion" (
  "institucion_id" INT PRIMARY KEY,
  "rut" varchar(12) NOT NULL,
  "nom_institucion" varchar(50) NOT NULL,
  "nom_responsable" varchar(50) NOT NULL,
  "contacto_email" varchar(50) NOT NULL,
  "contacto_phone" varchar(15) NOT NULL,
  "direccion" varchar(50),
  "region_id" integer,
  "comuna_id" integer
);

CREATE TABLE "proveedor" (
  "proveedor_id" INT PRIMARY KEY,
  "nom_proveedor" varchar(50) NOT NULL,
  "empresa_id" int
);

CREATE TABLE "region" (
  "region_id" INT PRIMARY KEY,
  "nom_region" varchar(50) NOT NULL
);

CREATE TABLE "comuna" (
  "comuna_id" INT PRIMARY KEY,
  "nom_comuna" varchar(50) NOT NULL,
  "region_id" int
);

ALTER TABLE "comuna" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("region_id");

ALTER TABLE "institucion" ADD FOREIGN KEY ("comuna_id") REFERENCES "comuna" ("comuna_id");

ALTER TABLE "institucion" ADD FOREIGN KEY ("region_id") REFERENCES "comuna" ("region_id");

ALTER TABLE "product" ADD FOREIGN KEY ("area_id") REFERENCES "area" ("area_id");

ALTER TABLE "product" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("empresa_id");

ALTER TABLE "product" ADD FOREIGN KEY ("search_by") REFERENCES "users" ("user_id");

ALTER TABLE "empresa" ADD FOREIGN KEY ("comuna_id") REFERENCES "comuna" ("comuna_id");

ALTER TABLE "empresa" ADD FOREIGN KEY ("region_id") REFERENCES "comuna" ("region_id");

ALTER TABLE "proveedor" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("empresa_id");
